version: "3.2"
services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/nginx.Dockerfile
    ports:
        - 80:80
    depends_on:
        - fastapi

  fastapi:
    build:
      context: .
      dockerfile: ./dockerfiles/fastapi/fastapi.Dockerfile
    depends_on:
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
    - ./redis-data:/data
    command:
      # Save if 50 keys are added in every 10 seconds
      - "--save 10 50"
    extra_hosts:
      - host.docker.internal:host-gateway

  redisinsight: # redis db visualization dashboard
    container_name: redisinsight-cont
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

volumes:
  redis-data:
  redisinsight:
